customers:
  rgi_indusind:
    name: RGI IndusInd
    description: Reliance General Insurance - IndusInd Bank Partnership
    postman_collection: collections/RGI_premium_APIs.postman_collection
    environments:
    - dev
    - sit
    - uat
    - production
    active: true
  indusind_nippon_life_insurance:
    name: IndusInd Nippon Life Insurance
    description: IndusInd Nippon Life Insurance
    postman_collection: collections/indusind_nippon_life_insurance.postman_collection.json
    environments:
    - dev
    active: true
    postman_collections:
    - collections/indusind_nippon_life_insurance/1770332518_Super_Suraksha.postman_collection.json
    - collections/indusind_nippon_life_insurance/1770332518_Generate_PaymentURL.postman_collection.json
    - collections/indusind_nippon_life_insurance/1770332518_Communication_APIs.postman_collection.json
    - collections/indusind_nippon_life_insurance.postman_collection.json
    - collections/indusind_nippon_life_insurance/1770332518_Agent_Microsite.postman_collection.json
